In [2]:
import numpy as np

In [3]:
## 1D Array
arr = np.array([1,2,3])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [4]:
arr = np.array([1, 2, 3, 4, 5])
arr.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [5]:
## 2D Array
arr = np.array(([1, 2, 3, 4, 5],[6,7,8,9,10]))
print(arr)
arr.shape


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [6]:
arr = np.arange(10).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Attributes
arr = np.array(([1,2,3],[4,5,6]))
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(2, 3)
2
6
int64
8


In [14]:
# Vectorises Operators
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Elementwise Functions
arr = np.array([1,4,9])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[ 0.84147098 -0.7568025   0.41211849]
[0.         1.38629436 2.19722458]


In [32]:
# Array Slicing and Indexing

arr = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))

print(arr, end="\n-----------\n")
print(arr[0],end="\n-----------\n")
print(arr[0][0], end="\n-----------\n")

print(arr[1:,2:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------
[1 2 3 4]
-----------
1
-----------
[[ 7  8]
 [11 12]]


In [34]:
# Statstics 

data = np.array([1, 2, 3, 4, 5])
print("Data :" , data)
mean = data.mean()
print("Mean :" , mean)

sd = data.std()
print("Standard Deviation :" , sd)

normal = (data - mean)/sd
print("Normal :" , normal)



Data : [1 2 3 4 5]
Mean : 3.0
Standard Deviation : 1.4142135623730951
Normal : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
# Logical operations

data = np.array([1, 2, 3, 4, 5,7,8,9,10])

print(data > 5)
print(data < 5)
print(data >= 5)
print(data <= 5)
print(data == 5)
print(data != 5)

print(data[(data >= 5) & (data < 8)] )


[False False False False False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False  True  True  True  True  True]
[ True  True  True  True  True False False False False]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[5 7]
